// Rare earth element reference prices — OTC market, not exchange-traded.
// Prices sourced from Fastmarkets, Metal Pages and industrial market data.
// Update periodically as market conditions change.
export const REE_PRICES = [
  {
    id: 'dysprosium',
    symbol: 'Dy',
    name: 'Dysprosium',
    grade: 'Dy₂O₃ 99.5%',
    priceUsd: 189,
    unit: 'per kg',
    ytdChange: '+102%',
    ytdUp: true as boolean | null,
    exportControlled: true,
    note: 'China Announcement 18 (Apr 2025)',
    href: '/markets/rare-earths/dysprosium',
    updatedAt: '2026-04',
  },
  {
    id: 'terbium',
    symbol: 'Tb',
    name: 'Terbium',
    grade: 'Tb₄O₇ 99.9%',
    priceUsd: 840,
    unit: 'per kg',
    ytdChange: '+40%',
    ytdUp: true as boolean | null,
    exportControlled: true,
    note: 'China Announcement 18 (Apr 2025)',
    href: '/markets/rare-earths/terbium',
    updatedAt: '2026-04',
  },
  {
    id: 'ndpr',
    symbol: 'NdPr',
    name: 'Neodymium / Praseodymium',
    grade: 'NdPr oxide, magnet grade',
    priceUsd: 144,
    unit: 'per kg',
    ytdChange: 'Stable',
    ytdUp: null as boolean | null,
    exportControlled: false,
    note: 'Core NdFeB magnet feedstock',
    href: '/markets/rare-earths/ndpr',
    updatedAt: '2026-04',
  },
  {
    id: 'neodymium',
    symbol: 'Nd',
    name: 'Neodymium',
    grade: 'Nd₂O₃ 99.5%',
    priceUsd: 149,
    unit: 'per kg',
    ytdChange: 'Stable',
    ytdUp: null as boolean | null,
    exportControlled: false,
    note: 'Highest-demand REE globally',
    href: '/markets/rare-earths/neodymium',
    updatedAt: '2026-04',
  },
  {
    id: 'samarium',
    symbol: 'Sm',
    name: 'Samarium',
    grade: 'Sm₂O₃ 99.9%',
    priceUsd: 4.50,
    unit: 'per kg',
    ytdChange: 'Rising',
    ytdUp: true as boolean | null,
    exportControlled: true,
    note: 'China Announcement 18 (Apr 2025)',
    href: '/markets/rare-earths/samarium',
    updatedAt: '2026-04',
  },
  {
    id: 'yttrium',
    symbol: 'Y',
    name: 'Yttrium',
    grade: 'Y₂O₃ 99.9%',
    priceUsd: 3.80,
    unit: 'per kg',
    ytdChange: 'Rising',
    ytdUp: true as boolean | null,
    exportControlled: true,
    note: 'China Announcement 18 (Apr 2025)',
    href: '/markets/rare-earths/yttrium',
    updatedAt: '2026-04',
  },
]
